ittiam-systems/libavc

- decoder/ih264d_api.c
> decoder: Fix the size check for arguments to decode call.

- fuzzer/ossfuzz.sh
oss-fuzz.sh: Enable svc enc fuzzer
> oss-fuzz.sh: Enable svc enc fuzzer

- encoder/svc/isvce_api.c
- encoder/svc/isvce_process.c
> Fixes for oss-fuzz:556440

- decoder/svc/isvcd_api.c
- decoder/svc/isvcd_structs.h
> Resolve the issue of pps and sps counter overflow

- decoder/svc/isvcd_nal_parse.c
> Resolve the issue of non-vcl buffer overflow in nal_parse

- decoder/svc/isvcd_api.c
- decoder/svc/isvcd_parse_epslice.c
> Resolved invalid memory access to Weighted pred offsets

- decoder/svc/isvcd_parse_epslice.c
BUG=oss-fuzz: 56023, 56050, 56089
> svcdec: Bug fix in mark_err_slice_skip funtion w.r.t thread creation

- decoder/svc/isvcd_parse_headers.c
- decoder/svc/isvcd_parse_slice.c
> svcdec: Bug fix in header and SPS parsing w.r.t non dyadic SVC decoding

- decoder/svc/isvcd_ii_pred.c
> svcdec: Fix for out of bound index in ii_pred

- encoder/ih264e_api.c
Bug: oss-fuzz:57331
Test: avc_enc_fuzzer
> encoder: Add checks for ME search algorithm

- decoder/svc/isvcd_parse_ebslice.c
- decoder/svc/isvcd_process_epslice.c
> svcdec: Fix for out of range reference index during base mode flag

- decoder/ih264d_parse_slice.c
Bug: oss-fuzz:55598, oss-fuzz:57605, oss-fuzz:55641
Test: avc_dec_fuzzer
> decoder: handle error returned by ih264d_decode_gaps_in_frame_num

- fuzzer/avc_dec_fuzzer.cpp
- test/decoder/main.c
> decoder: set keep_threads_active to 1 in the testbench and fuzzer

- fuzzer/avc_dec_fuzzer.cpp
> decoder: limit number of calls to decode header

- Android.bp
sort listings in alphabetical order
Test: Build
> libavc: tidy up android bp - 2

- decoder/ih264d_api.c
> decoder: join threads in flush mode

- encoder/irc_bit_allocation.c
For large intra frame intervals or for a choice of bit rate that causes large bits per frame, it possible that while computing number of bits available in the gop overflow the datatype bounds. For these calculations use number_t as this offers wider space
Bug: oss-fuzz-63044
Test: avc_enc_fuzzer
Change-Id: Ifee9130f0021f77905aea67832abc044537088e5
> libavcenc: use number_t while computing number of bits in period

- encoder/ih264e_api.c
- encoder/ih264e_encode.c
> libavcenc: fix build issues on android

- decoder/svc/isvcd_api.c
- decoder/svc/isvcd_parse_headers.c
- decoder/svc/isvcd_structs.h
ID#
65031
65035
65057
65059
65060
65132
65172
65482
> svcdec: oss-fuzz bug fixes

- tests/DynamicConfig.xml
- tests/README.md
Bug: 308464572
Test: atest AvcEncTest
Change-Id: I20387647c54e665e5b632ac0e791e259ddb519ff
> Use media file zip from dl.google.com

- decoder/ih264d_parse_headers.c
Bug: 325468696
Test: atest android.mediav2.cts.DecoderDynamicColorAspectTest
> libavc: Add dynamic color aspects support

- decoder/ih264d_utils.c
Test: Build
Change-Id: Ic9212b86efbc54724c09164776169bfeafb15d7b
> libavc: Fix poc counts for idr slice

- .vscode/c_cpp_properties.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- Added .vscode directory with tasks.json, settings.json, c_cpp_properties.json, and launch.json.
- Configures the Build button to build the project.
- Configures Run and Debug panel to run avcdec and avcenc test benches.
Test: Build
Change-Id: Ifee9130f0041f77907a1a668227bc049270898e1
> libavc: Add VSCode configuration files for Linux & MacOS

- decoder/ih264d_parse_headers.c
Test: atest android.mediav2.cts.DecoderDynamicColorAspectTest
Change-Id: Id64ddb874efe1ab51cd9b2359bfa9526bc1ccd6e
> libavc: Fix dynamic color aspects support

- encoder/ih264e_encode.c
Change-Id: I5f5cf7f705d389f6938fc641daa558bedfbc462b
> avcenc: Fixed thread handle parameter

- decoder/svc/isvcd_parse_ebslice.c
- decoder/svc/isvcd_parse_eislice.c
- decoder/svc/isvcd_parse_epslice.c
- decoder/svc/isvcd_parse_headers.c
- decoder/svc/isvcd_parse_slice.c
- decoder/svc/isvcd_parse_slice.h
- decoder/svc/isvcd_process_ebslice.c
- decoder/svc/isvcd_process_ebslice.h
- decoder/svc/isvcd_process_epslice.c
- decoder/svc/isvcd_process_epslice.h
- decoder/svc/isvcd_structs.h
- decoder/svc/isvcd_thread_parse_decode.c
- decoder/svc/isvcd_thread_parse_decode.h
- decoder/svc/isvcd_utils.c
Bug: 434978682
Bug: 435086517
Test: ./svc_dec_fuzzer
Change-Id: I5c432aa63b0975b76baa5e59a819278087b65218
> libavcdec: resolve heap buffer overflows in svc and handle overflows
