ittiam-systems/libavc

encoder/svc/isvce_api.c
encoder/svc/isvce_encode.c

Fixed incorrect outbuf size assignment in 'isvce_get_buf_info'
BUG=oss-fuzz:55639
BUG=oss-fuzz:55643

Fixes for oss-fuzz:556439 and oss-fuzz:556443

---

encoder/riscv/svc/isvce_function_selector.c
encoder/riscv/svc/isvce_platform_macros.h
encoder/svc/isvce_downscaler.c
encoder/svc/isvce_ibl_eval.c
encoder/svc/isvce_rc_utils.c
encoder/svc/isvce_residual_pred.c

riscv4 soong builds were failing due to incorrect usage of 'ARM' macro. This was fixed.

svcenc: fixed riscv4 soong build errors

---

fuzzer/svc_enc_fuzzer.cpp

420sp was not being tested in svcenc fuzzer. This is now being tested.
Closes #7

svcenc: 420sp support added to fuzzer

---

encoder/svc/isvce_api.c
encoder/svc/isvce_encode.c
encoder/svc/isvce_utils.c
encoder/svc/isvce_utils.h

For certain configurations of the fuzzer input, the minimum output buffer size is insufficient.
The minimum value has been doubled in this commit.
BUG=oss-fuzz:55797

svcenc: increased minimum outbuf size

---

encoder/svc/isvce_cabac.c

If 'u4_strm_buf_offset == 0' when 'isvce_cabac_flush' is called, then 'carry' is implicitly 0.
'u4_strm_buf_offset == 0' implies stream buffer is empty.
Invocation of 'isvce_cabac_flush' implies all MB's in a slice have been encoded.
BUG = ossfuzz:56137

svcenc: fixed incorrect streamBuf accesses

---

encoder/svc/isvce_api.c
encoder/svc/isvce_process.c

Certain ILP buffers are reset when encoded bitrate exceeds configured bitrate. The size used for one of them was incorrect.

svcenc: fixed a bug in low bitrate encodes

---

Android.bp
test/Android.bp

Minor changes in names of defaults in order get consistency between libraries and applications being built.
Test: builds

Format Android.bp files

---

encoder/svc/isvce_cabac.c

If 'u4_strm_buf_offset < 4' when 'isvce_cabac_flush' is called, then EPB could not have been inserted into the stream buffer.
BUG = ossfuzz:56816

svcenc: fixed incorrect EPB checks

---

fuzzer/avc_enc_fuzzer.cpp

included <tuple> to fix errors seen when using some compilers

avc_enc_fuzzer: Add #include <tuple>

---

encoder/ih264e_process.c

Using incorrect stride during copy from source buffer to intermediate buffer. This is corrected

avcenc: Fix out of bound read in initialize process context

---

encoder/svc/isvce_encode.c
encoder/svc/isvce_rc_mem_interface.c
encoder/svc/isvce_structs.h
encoder/svc/isvce_utils.c
encoder/svc/isvce_utils.h

RC uses int32_t for storing multiple quantities related to bits in a given period.
'isvce_svc_frame_params_validate' has been added, which queries RC API for the relevant quantities and returns with and error if computations involving those quantities exceed INT32_MAX.
BUG = ossfuzz:274221347
BUG = ossfuzz:274265498

svcenc: RC bitrate overflows prevented

---

fuzzer/ossfuzz.sh

When oss-fuzz enables undefined sanitizer, enable only the following
- signed-integer-overflow
- unsigned-integer-overflow
- bounds

ossfuzz: opt-in to integer and bounds sanitizers in undefined sanitizer

---

encoder/svc/isvce_process.c

The ILP MV struct pointer will be set to NULL for I slices and for spatial layer ID 0. A NULL check ought to be used in all places that access this pointer. This was missing in 2 places and has been added.

svcenc: nullSan errors in ILPMv fixed

---

encoder/ih264e_encode.c

In some cases, s_inp_buf and s_out_buf on stack in ih264e_encode() can be accessed unininitialized. This is fixed by initializing these two structures.
Bug: oss-fuzz:57333
Bug: 274906999
Test: avc_enc_fuzzer

encoder: Initialize s_inp_buf and s_out_buf to zero in ih264e_encode

---

decoder/mvc/imvcd_defs.h

The worst case FGC SEI payload size in cojunction with the worst case sizes of other NALU's can be significantly larger than the default bitstream buffer size of 256000. It is now set to the sum of 256000 and MAX_FGC_SEI_SIZE.
Bug: ossFuzz:58190

mvcdec: Bitstream buf allocatiion accounts for FGC SEI

---

encoder/ih264e_encode.c
encoder/ih264e_encode_header.h
encoder/ih264e_error.h
encoder/ih264e_process.c
encoder/ih264e_utils.c

During encoding, if encoder encounters an error, the library returns the same. If the application ignores it and feeds further input, library while processing the new input is facing a null dereference.
1. Added a error check in encode API call before processing input
2. Made entropy bitstream buffer overflow errors non-fatal.
Bug: 187499509
Test: POC in bug descriptions
atest VtsHalMediaC2V1_0TargetVideoEncTest
atest -c CtsMediaV2TestCases:CodecEncoderTest

libavcenc: fix null buffer dereferencing

---

encoder/svc/isvce_sub_pic_rc.c

A 'consumption ratio' is computed for every MB when in-frame RC is enabled. This computation can result in divide-by-zeros in certain circumstances. Such cases are now appropriately handled.
Bug: ossFuzz:60828

svcenc: Handling frames with few MB's in In-frame RC

---

decoder/mvc/imvcd_dpb_manager.c
decoder/mvc/imvcd_slice_functions.c

[x] For certain sequences of modification_of_pic_nums_idc,
OOB accessses of the aps_mod_dpb buffer within mvc_dpb_manager_t
struct could occur. This case has been now detected
and handled.
[x] Removed unused variables in 'imvcd_slice_functions.c'.

mvcdec: Fixes for OOB accesses of refPicList

---

test/decoder/main.c

decoder: add "summary" before codec exit with error message

---

encoder/ih264e_process.c

At the end of encoding of a frame, the entropy thread communicates the encoded bit stream size to rc module for update. After this update, if rc decides to skip the frame due to vbv overflow, the bitstream context is reset and frame is marked for skip.
Due to an oversight, if entropy encoding sees an error, then this update is happening at the end of each row. Now rc has decided to skip the frame and the context is reset. As the bitstream context is reset, other threads are unaware of this problem and continue encoding.
This is causing issues.
Restrict the rc update to the thread that entropy code the last row.
Bug: oss-fuzz:59543
Bug: 285891354
Test: avc_enc_fuzzer
Change-Id: If45a5f34abb59ece812733af8f54f72ae5474d03

libavcenc: do not reset status before all threads are made aware

---

encoder/svc/isvce_encode.c
encoder/svc/isvce_rate_control.c
encoder/svc/isvce_utils.c
encoder/svc/isvce_utils.h

RC uses int32_t to store bitrates and other
parameters internally. For specific magnitudes of
bitrate, framerate, and GOP period, this can
result in signed integer overflow. This is now
detected before calls to RC init.
Note that calls to the 'ISVCE_CMD_CTL_SET_BITRATE' API can also result in this behaviour but it will be appropriately handled by 'isvce_svc_frame_params_validate'.
Bug = ossfuzz:63053

svcenc: RC parameters verified before RC init

---

common/x86/svc/isvc_mem_fns_ssse3.c
encoder/svc/isvce_api.c

svcenc: Enabled and verified 420sp inputs

---

tests/AndroidTest.xml
tests/DynamicConfig.xml
tests/README.md

AvcEncTest: Use MediaPreparer to download test files

---

decoder/ih264d_utils.c

Make use of cur_pps to compute the max number of frames in decode gaps in frame num
Bug: oss-fuzz-61655
Test: avc_dec_fuzzer

libavcdec: Fix timeout issue in AVC Decoder

---

encoder/ih264e_api.c
encoder/ih264e_encode.c

Before applying the config params (dimensions), the api is validating the input buffer dimensions. This causes encode fails wrongly. This is corrected.

libavcenc: validate dimensions after applying config params

---

decoder/mvc/imvcd_api.c
decoder/mvc/imvcd_api_utils.c
decoder/mvc/imvcd_api_utils.h
decoder/mvc/imvcd_defs.h

There can be cases where there are multiple SEI payloads within a single SEI NAL. In the particular case where the payload comprises exclusively of FGC data, the size of the NAL can exceed the size of the 'dynamic bitstream buffer' which is used to pass the NALU onto its appropriate parser.
This commit adds 'imvcd_bitstream_buf_realloc' which re-allocates the 'dynamic bitstream buffer' such that any arbitrarily sized NALU can be stored without a heap overflow.
Bug = ossfuzz:64286

mvcdec: Fixed heap overflow during SEI parsing

---

decoder/svc/isvcd_api.c
decoder/svc/isvcd_parse_ebslice.c
decoder/svc/isvcd_parse_epslice.c
decoder/svc/isvcd_process_epslice.c
decoder/svc/isvcd_structs.h

Resolution level initialization is tracked in inter layer prediction functions
Bug = ossfuzz:62290

svcdec: Fixes for NULL dereferencing in inter-layer functions

---

decoder/svc/isvcd_api.c
decoder/svc/isvcd_intra_resamp.c
decoder/svc/isvcd_intra_resamp.h
decoder/svc/isvcd_parse_ebslice.c
decoder/svc/isvcd_parse_eislice.c
decoder/svc/isvcd_parse_epslice.c
decoder/svc/isvcd_parse_slice.c
decoder/svc/isvcd_process_epslice.c
decoder/svc/isvcd_structs.h

svcdec fuzzer: Multiple issues reported in the month of november and december 2023 were fixed

Oss fuzz svcdec fixes

---

encoder/svc/isvce_utils.c
encoder/svc/isvce_utils.h

'isvce_svc_rc_params_validate' was not being invoked prior to
call to 'isvce_rc_init'. This resulted in an erroneous state
within RC's context wherein the instantaneous estimate for the
texture bits for the frame being processed exceeded INT_MAX.
'isvce_svc_rc_params_validate' has code that detects such a
state and is now being correctly invoked where apprpriate.
Bug = ossfuzz:63175

svcenc: Integer overflow in irc_ba_get_cur_frm_est_texture_bits

---

decoder/ih264d_sei.c
decoder/mvc/imvcd_api.c

Although the fag end of both the NALU and the bitstream buffer
is being parsed, not all FGC SEI symbols would have been
decoded semantically. This commit detects and returns an error in this situation.
Bug = ossfuzz:65418

mvcdec: Heap overflow in 'ih264d_parse_fgc'

---

TEST_MAPPING
tests/Android.bp

After some time of running these in postsubmit, these will be changed to presubmit.
- Added AvcEncTest to device-tests test suite
- Also run bpfmt on test/Android.bp
Bug: 304383609
Test: atest AvcEncTest
Change-Id: Ic18b25d8ed27313b6e3a984259af1215ae240c9e

Enable unit tests in postsubmit

---

Android.bp

There hasn't been a non-neon platform build in years.
Bug: 330929681
Test: Builds
Change-Id: I712c2111722a17ecf55ab36e8069275c74379256

Remove useless `neon:` clause.

---

decoder/mvc/imvcd_api.c

In some erroneous fuzzer bistreams, the slice data requires more parsing than what was implied by the distance between successive start codes. The primary culprit is the NEXTBITS macro which requires reading 4 additional bytes of the bitstream buffer. To alleviate this, 4 bytes per 4x4 TU have been additionally allocated to the bitstream buffer.
Bug = ossfuzz:66989

mvcdec: Heap overflow in 'ih264d_read_coeff4x4_cabac'

---

decoder/svc/isvcd_parse_slice.c

svcdec: Added fixes for heap buffer overflow fuzzers
Bug = ossfuzz:68807, ossfuzz:69682

oss-fuzz heap buffer overflow and timeout

---

decoder/svc/isvcd_api.c

svcdec: Handled timeout by returning status of the error

---

fuzzer/svc_dec_fuzzer.cpp

svcdec: Limit decode calls to a maximum of 100 to prevent potential timeouts with fuzzers

Limit decode calls to a maximum of 100 to prevent potential timeouts with fuzzers

---

decoder/ih264d_api.c

- Changed hardcoded index [0] to loop variable [i] in ithread_mutex_init call
- Ensures correct initialization of both mutexes in the loop
Test: ./avcdec

libavc : Fix mutex initialization index in apv_proc_start_mutex

---

CMakeLists.txt
README.md
cmake/toolchains/aarch32_toolchain.cmake
cmake/toolchains/aarch64_toolchain.cmake
cmake/toolchains/android_toolchain.cmake
cmake/utils.cmake
common/common.cmake
decoder/arm/ih264d_function_selector.c
decoder/ih264d_dpb_mgr.c
decoder/libavcdec.cmake
encoder/arm/ih264e_function_selector.c
encoder/libavcenc.cmake
fuzzer/avc_dec_fuzzer.cmake
fuzzer/avc_enc_fuzzer.cmake

libavc : Enable support for MacOS

---

decoder/ih264d_dpb_mgr.c
decoder/ih264d_parse_headers.c
decoder/ih264d_structs.h

In avc MaxFrameNum can be 65536 which is of 17 bits due to which interger overflow was happening for i2_max_frm_num and ui_max_frame_num. This has been fixed.
Bug: 369676522
Test: poc in bug description
Change-Id: I858eea6bf8eea1e2cee6d4a7c28a84705eb51792

libavcdec: Fix integer overflow issue in ui_max_frame_num

---

Android.bp

Bug: 376303949
Test: Build and review

libavc: remove unused KEEP_THREADS_ACTIVE flag in Android.bp

---

Android.bp
CMakeLists.txt
common/ih264_list.c
common/ih264_list.h
common/ithread.c
common/ithread.h
encoder/ih264e_api.c
encoder/ih264e_defs.h
encoder/ih264e_encode.c
encoder/ih264e_master.h
encoder/ih264e_structs.h
encoder/libavcenc.cmake

Currently avc encoder creates desired number of threads at the start of every frame and joins after frame is processed. This change modifies the thread creation part. Now the threads are created at the start of the sequence. Kept alive through out the sequence and joined at the end of the sequence. This helps in reduction of thread creation and deletion overhead.
This change does not effect the encoded bitstream. That is, encoded output with this change is same as encoded output without this change.
Bug:288998933

avcenc: add support for KEEP_THREADS_ACTIVE

---

encoder/ih264e_api.c
encoder/ih264e_encode.c
fuzzer/avc_enc_fuzzer.cpp

Adds proper thread pool shutdown on the last frame when KEEP_THREADS_ACTIVE is defined.
Moves mutex and conditional variable initialization/destruction to appropriate locations out of thread pool init and shutdown.
Calls retrieve_memrec before deinitialization in the fuzzer.
Test:  avcenc -c enc.cfg

avcenc: Fix thread management and memory cleanup

---

Android.bp
CMakeLists.txt
common/ih264_list.c
common/ih264_list.h
common/ithread.c
common/ithread.h
encoder/ih264e_api.c
encoder/ih264e_defs.h
encoder/ih264e_encode.c
encoder/ih264e_master.h
encoder/ih264e_structs.h
encoder/iv2.h
encoder/ive2.h
encoder/libavcenc.cmake
examples/avcenc/app.h
examples/avcenc/enc.cfg
examples/avcenc/main.c
fuzzer/avc_enc_fuzzer.cpp

Change-Id: If6c8c29d2b5b1322796b8b25dc74231d13b61243

avcenc: Replacing KEEP_THREADS_ACTIVE with runtime check

---

examples/avcenc/enc.cfg
fuzzer/avc_enc_fuzzer.cpp

Change-Id: I45b32621aa3d64b569e5ac6b7f23405aa1711c82

avcenc: Enabling keep_threads_active in cfg and avc_enc_fuzzer

---

examples/Android.bp

This change redefines the `cc_test` modules within the examples directory as `cc_binary` modules.
Previously, these `cc_test` modules were effectively acting as wrappers around executable binaries, solely for the purpose of generating test executables. This approach did not allow for the direct installation of these executables on devices.
Changing these modules to `cc_binary` allows the resulting executables are produced as standalone binaries, enabling their deployment and execution on test devices.
Bug: 414657128
Change-Id: I9caef8a5cf29c7d77b8bcd535f047a640c52285c

Redefine examples test modules as cc_binary

---

encoder/ih264e_api.c
encoder/ih264e_encode.c
encoder/ih264e_structs.h

Change-Id: I5f5cf7f705d389f6938fc641daa558bedfbc573c

avcenc: cleanup for thread pool memory handling
